fix(install-chrome.sh): Chrome install not working on ARM executors
CircleCI-Public/browser-tools-orb pull request #73
Opened 2023-07-17 10:19 UTC by itsyuvalcohen

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Chrome installations on ARM executors fails due to a bad architecture check causing it to use amd64 instead of arm64

### Description

Fixed ENV_IS_ARM variable

2023-07-17 15:11 UTC, ryanbourdais requested changes
Thanks for the contribution, I left a note in your changes

2023-07-17 15:11 UTC, ryanbourdais commented on src/scripts/install-chrome.sh
> +    ENV_IS_ARM=$(dpkg --print-architecture | grep arm64)
I just tried test running these changes and now most of the tests are failing, I think that this line should go back to how it was originally but replacing line 111 with `if [ "$ENV_IS_ARM" == "1" ]; then` would fix this issue

2023-07-17 15:58 UTC, itsyuvalcohen commented
> Thanks for the contribution, I left a note in your changes

I figured out google doesn't even publish google-chrome-stable for arm64, I think we should exit with an error saying it isn't supported

2023-07-17 16:07 UTC, ryanbourdais commented
> > Thanks for the contribution, I left a note in your changes
> 
> I figured out google doesn't even publish google-chrome-stable for arm64, I think we should exit with an error saying it isn't supported

If you would like to make that change on this PR I can get that merged in, otherwise I can just close this PR out.

2023-07-18 15:22 UTC, ryanbourdais approved these changes
Looks good to me

2023-07-18 15:23 UTC, merged

2024-07-11 03:30 UTC, m3thom commented
If I understand correctly, we should be able to install Chrome on ARM when this issue is resolved, no?
https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1